// client-react/src/App.js
import React, { useEffect } from "react";
import { BrowserRouter as Router, Route, Routes, Link } from "react-router-dom";
import Lobby from "./views/Lobby";
import Login from "./views/Login";
import Game from "./views/Game";
import Pending from "./views/Pending";
import {
  fetchGames,
  fetchPendingGames,
  upsertOngoingGame,
  upsertPendingGame,
  removePendingGame,
} from "./redux/actions";
import { useDispatch, useSelector } from "react-redux";

const App = () => {
  const dispatch = useDispatch();
  const player = useSelector((state) => state.player.player);
  const ongoingGames = useSelector((state) => state.ongoingGames.games);
  const pendingGames = useSelector((state) => state.pendingGames.games);

  const isParticipant = (game) => game.players.includes(player ?? "");

  useEffect(() => {
    const ws = new WebSocket("ws://localhost:9090/publish");
    ws.onopen = () => ws.send(JSON.stringify({ type: "subscribe" }));
    ws.onmessage = ({ data: gameJSON }) => {
      const game = JSON.parse(gameJSON);
      if (game.pending) {
        dispatch(upsertPendingGame(game));
      } else {
        dispatch(upsertOngoingGame(game));
        dispatch(removePendingGame(game));
      }
    };
    return () => {
      ws.send(JSON.stringify({ type: "unsubscribe" }));
      ws.close();
    };
  }, [dispatch]);

  useEffect(() => {
    const fetchData = async () => {
      const games = await fetchGames();
      games.forEach((game) => dispatch(upsertOngoingGame(game)));

      const pendingGames = await fetchPendingGames();
      pendingGames.forEach((game) => dispatch(upsertPendingGame(game)));
    };
    fetchData();
  }, [dispatch]);

  const myOngoingGames = ongoingGames.filter(isParticipant);
  const myPendingGames = pendingGames.filter(isParticipant);
  const otherPendingGames = pendingGames.filter((game) => !isParticipant(game));

  return (
    <Router>
      <div>
        <h1 className="header">Yahtzee!</h1>
        {player && <h2 className="subheader">Welcome player {player}</h2>}
        {player && (
          <nav>
            <Link className="link" to="/">
              Lobby
            </Link>

            <h2>My Games</h2>
            <h3>Ongoing</h3>
            {myOngoingGames.map((game) => (
              <Link key={game.id} className="link" to={`/game/${game.id}`}>
                Game #{game.id}
              </Link>
            ))}

            <h3>Waiting for players</h3>
            {myPendingGames.map((game) => (
              <Link key={game.id} className="link" to={`/pending/${game.id}`}>
                Game #{game.id}
              </Link>
            ))}

            <h2>Available Games</h2>
            {otherPendingGames.map((game) => (
              <Link key={game.id} className="link" to={`/pending/${game.id}`}>
                Game #{game.id}
              </Link>
            ))}
          </nav>
        )}
        <Routes>
          <Route path="/" element={<Lobby />} />
          <Route path="/login" element={<Login />} />
          <Route path="/game/:id" element={<Game />} />
          <Route path="/pending/:id" element={<Pending />} />
        </Routes>
      </div>
    </Router>
  );
};

export default App;

// client/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from "vue-router";
import { computed, onMounted, onUnmounted } from "vue";
import { useOngoingGamesStore } from "./stores/ongoing_games_store";
import * as api from "./model/api";
import { usePlayerStore } from "./stores/player_store";
import { usePendingGamesStore } from "./stores/pending_games_store";
import type { IndexedYahtzeeSpecs } from "./model/game";
import { is_finished } from "models/src/model/yahtzee.game";

const ongoingGamesStore = useOngoingGamesStore();
const pendingGamesStore = usePendingGamesStore();
const playerStore = usePlayerStore();

const isParticipant = (g: { players: string[] }) =>
  g.players.indexOf(playerStore.player ?? "") > -1;

const my_ongoing_games = computed(() =>
  ongoingGamesStore.games.filter((g) => isParticipant(g) && !is_finished(g))
);
const my_pending_games = computed(() =>
  pendingGamesStore.games.filter(isParticipant)
);
const other_pending_games = computed(() =>
  pendingGamesStore.games.filter((g) => !isParticipant(g))
);

onMounted(async () => {
  const ws = new WebSocket("ws://localhost:9090/publish");
  ws.onopen = () => ws.send(JSON.stringify({ type: "subscribe" }));
  ws.onmessage = ({ data: gameJSON }) => {
    const game = JSON.parse(gameJSON);
    if (game.pending) {
      pendingGamesStore.upsert(game);
    } else {
      ongoingGamesStore.upsert(game);
      pendingGamesStore.remove(game);
    }
  };
  onUnmounted(() => {
    ws.send(JSON.stringify({ type: "unsubscribe" }));
    ws.close();
  });

  const games = await api.games();
  games.forEach(ongoingGamesStore.upsert);

  const pending_games = await api.pending_games();
  pending_games.forEach(pendingGamesStore.upsert);
});
</script>

<template>
  <h1 class="header">Yahtzee!</h1>
  <h2 v-if="playerStore.player" class="subheader">
    Welcome player {{ playerStore.player }}
  </h2>
  <nav v-if="playerStore.player">
    <RouterLink class="link" to="/">Lobby</RouterLink>

    <h2>My Games</h2>
    <h3>Ongoing</h3>
    <RouterLink
      class="link"
      v-for="game in my_ongoing_games"
      :to="`/game/${game.id}`"
      >Game #{{ game.id }}</RouterLink
    >

    <h3>Waiting for players</h3>
    <RouterLink
      class="link"
      v-for="game in my_pending_games"
      :to="`/pending/${game.id}`"
      >Game #{{ game.id }}</RouterLink
    >

    <h2>Available Games</h2>
    <RouterLink
      class="link"
      v-for="game in other_pending_games"
      :to="`/pending/${game.id}`"
      >Game #{{ game.id }}</RouterLink
    >
  </nav>

  <RouterView class="main" />
</template>

<style>
#app {
  background-color: rgb(243, 244, 245);
  margin: 0;
  padding: 0.6rem;
}
html {
  height: 100%;
}
body {
  width: 1024px;
  height: 100%;
  margin: 0 auto;
  background-color: rgb(20, 30, 47);
  padding: 0;
}
nav {
  margin-left: 5%;
  float: right;
}
.link {
  margin: 0.3rem;
  display: block;
}
</style>
