// client-react-ts/src/routes/game.tsx
import { useParams } from "react-router";
import { useAppSelector } from "../store/hooks";
import "./game.css";
import { ScoreCard } from "../components/score-card";
import { is_finished, scores } from "models/src/model/yahtzee.game";
import { DiceRoll } from "../components/dice-roll";

export function Game() {
  const params = useParams<{ gameId: string }>();

  const player = useAppSelector((state) => state.player.username);
  const game = useAppSelector((state) =>
    state.ongoingGames.find((g) => g.id === Number(params.gameId))
  );

  console.log({ player, game, params });

  if (!player || !game) return;

  const enabled = player === game.players[game.playerInTurn];

  const finished = is_finished(game);

  const standings = scores(game)
    .map<[string, number]>((s, i) => [game.players[i], s])
    .sort(([_, score1], [__, score2]) => score2 - score1);

  return (
    <div>
      <div className="meta">
        <h1>Game #{game.id}</h1>
      </div>
      <ScoreCard game={game} player={player} enabled={enabled} />
      <DiceRoll game={game} player={player} enabled={enabled} />
      {finished && (
        <div className="scoreboard">
          <table>
            <thead>
              <tr>
                <td>Player</td>
                <td>Score</td>
              </tr>
            </thead>
            <tbody>
              {standings.map((row) => (
                <tr className={row[0] == player ? "current" : undefined}>
                  <td>{row[0]}</td>
                  <td>{row[1]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// client/src/views/Game.vue
<script setup lang="ts">
import { useOngoingGamesStore } from "@/stores/ongoing_games_store";
import DiceRoll from "../components/DiceRoll.vue";
import ScoreCard from "../components/ScoreCard.vue";
import { useRoute, useRouter } from "vue-router";
import { computed, ref, watch } from "vue";
import { usePlayerStore } from "@/stores/player_store";
import { is_finished, scores } from "models/src/model/yahtzee.game";

const ongoingGameStore = useOngoingGamesStore();
const playerStore = usePlayerStore();
const route = useRoute();
const router = useRouter();

let id = ref(parseInt(route.params.id.toString()));
watch(
  () => route.params.id,
  (newId) => (id.value = parseInt(newId.toString()))
);
const game = computed(() => ongoingGameStore.game(id.value));
const enabled = computed(
  () =>
    game.value !== undefined &&
    playerStore.player === game.value.players[game.value.playerInTurn]
);
const finished = computed(
  () => game.value === undefined || is_finished(game.value)
);
const standings = computed(() => {
  if (game.value === undefined) return [];
  const g = game.value;
  const standings: [string, number][] = scores(g).map((s, i) => [
    g.players[i],
    s,
  ]);
  standings.sort(([_, score1], [__, score2]) => score2 - score1);
  return standings;
});

if (playerStore.player === undefined) router.push(`/login?game=${id.value}`);
else if (game.value === undefined) router.replace("/");
</script>

<template>
  <div v-if="game && playerStore.player" class="game">
    <div class="meta">
      <h1>Game #{{ id }}</h1>
    </div>
    <ScoreCard
      class="card"
      :game="game"
      :player="playerStore.player"
      :enabled="enabled"
    />
    <DiceRoll
      v-if="!finished"
      class="roll"
      :game="game"
      :player="playerStore.player"
      :enabled="enabled"
    />
    <div v-if="finished" class="scoreboard">
      <table>
        <thead>
          <tr>
            <td>Player</td>
            <td>Score</td>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="row in standings"
            :class="row[0] == playerStore.player ? 'current' : undefined"
          >
            <td>{{ row[0] }}</td>
            <td>{{ row[1] }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
<style>
.roll {
  margin: 0.3rem 1rem;
}
.scoreboard {
  display: inline-block;
  margin: 0.3rem 1rem;
}
.scoreboard thead {
  font-weight: bold;
  font-size: large;
}
.scoreboard > table {
  border: 1px solid black;
  border-collapse: collapse;
}
.scoreboard td {
  border: 1px solid black;
  border-collapse: collapse;
  padding: 0.2rem;
}
.current {
  font-weight: bold;
  background-color: firebrick;
  color: lavenderblush;
}
.game {
  contain: content;
}
.card {
  float: left;
}
</style>
